DROP TABLE user_table if EXISTS;
DROP TABLE company if EXISTS;
DROP TABLE giftcard if EXISTS;
DROP TABLE MEAL if EXISTS;

CREATE TABLE USER_TABLE (
id IDENTITY NOT NULL PRIMARY KEY,
name VARCHAR(255)
);

CREATE TABLE COMPANY (
id IDENTITY NOT NULL PRIMARY KEY,
name VARCHAR(255),
balance DECIMAL(18,2)
);

CREATE TABLE GIFTCARD (
id IDENTITY NOT NULL PRIMARY KEY,
user_id BIGINT,
company_id BIGINT,
amount DECIMAL(18,2),
creation_date DATE,
expiry_date DATE
);

CREATE TABLE MEAL (
id IDENTITY NOT NULL PRIMARY KEY,
user_id BIGINT,
company_id BIGINT,
amount DECIMAL(18,2),
creation_date DATE
);
